# Use an official Python runtime as a parent image
FROM python:3.9.13-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Make port 5000 available to the world outside the container
EXPOSE 5000

# Define environment variables
ENV FLASK_APP=backend.app

# Run the application using Gunicorn when the container starts
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "backend.app:app"]
