# Use an official Python runtime as a parent image
FROM python:3.9.13-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt && gunicorn --version

# Add local binary path to PATH in case gunicorn is installed there
ENV PATH="/root/.local/bin:${PATH}"

# Copy the current directory contents into the container
COPY . .

# Expose port 5000
EXPOSE 5000

# Run the application using Gunicorn
CMD ["python", "-m", "gunicorn", "--bind", "0.0.0.0:5000", "backend.app:app"]
